name: Trigger auto deployment for mlops-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mlops-app-AutoDeployTrigger-ef0ef267-2a2a-4098-89fb-bb7b25cb5f4d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MLOPSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MLOPSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MLOPSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ca42ac5b3444acr.azurecr.io
          registryUsername: ${{ secrets.MLOPSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MLOPSAPP_REGISTRY_PASSWORD }}
          containerAppName: mlops-app
          resourceGroup: Finsure
          imageToBuild: ca42ac5b3444acr.azurecr.io/mlops-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


